"""Fail the build if authoring-tool traces appear in anything shipped.

Run in CI and before every release.

Two categories are deliberately NOT flagged, because they are subject matter rather
than provenance:

1. MITRE ATT&CK content. ATT&CK names real malware (GeminiDuke), cites real research
   (IBM AI-generated content), documents LLM abuse as a technique (T1683), and
   publishes a campaign called "Anthropic AI-orchestrated Campaign" (C0062, the
   GTG-1002 activity). Stripping any of that would corrupt the dataset. Files derived
   from ATT&CK are checked only for document metadata, never for vocabulary.

2. This file, which necessarily contains the list of names it searches for.

    python tools/check_provenance.py
"""
from __future__ import annotations

import re
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SELF = Path(__file__).name

# Assistant and vendor names, matched on word boundaries so "such as an air-gapped"
# does not trip "as an ai". Split into two groups by how conclusive a match is.
# "cursor" is deliberately absent: it is a CSS property, and the noise would
# train people to ignore this check.
VENDORS = ["claude", "anthropic", "chatgpt", "openai", "copilot", "codeium",
           "github copilot", "bard", "perplexity"]
PHRASES = [r"as an ai (assistant|language model)", r"i am an ai\b",
           r"\bai-generated\b", r"generated by (an )?ai\b",
           r"as a large language model", r"i cannot browse the internet",
           r"knowledge cutoff", r"my training data"]
LIBRARIES = ["openpyxl", "python-docx", "docxtemplater", "reportlab"]

# Anything downstream of ATT&CK carries MITRE's vocabulary, not ours.
ATTACK_DERIVED = ("attack_actors", "attack_techniques", "attack_detection",
                  "attack_analytics", "attack_log_sources", "tool_data",
                  "assess.html", "tid-cmm-assessment.html", "techniques.json",
                  "model.json", "example-report.json")

TEXT_SUFFIXES = {".md", ".yaml", ".yml", ".py", ".js", ".html", ".css", ".json",
                 ".csv", ".txt", ".cff", ".xml", ".svg"}
SKIP_DIRS = {".git", "node_modules", "__pycache__", ".pytest_cache", ".venv"}


def _skip(p: Path) -> bool:
    return (any(d in p.parts for d in SKIP_DIRS)
            or p.name == SELF
            or any(k in p.name for k in ATTACK_DERIVED))


# Proper nouns of published ATT&CK objects. These are names of things in the threat
# landscape, valid anywhere including prose that explains this very exemption.
ALLOWED_PROPER_NOUNS = ["anthropic ai-orchestrated campaign"]


def scan_text(text: str) -> list[str]:
    low, hits = text.lower(), []
    for v in VENDORS:
        for m in re.finditer(rf"\b{re.escape(v)}\b", low):
            window = low[max(0, m.start() - 30): m.end() + 60]
            if any(n in window for n in ALLOWED_PROPER_NOUNS):
                continue
            hits.append(f"{v!r}: ...{low[max(0, m.start()-50):m.end()+50].strip()[:100]}...")
    for pat in PHRASES:
        for m in re.finditer(pat, low):
            hits.append(f"phrase {m.group(0)!r}")
    return hits


def check_text_files() -> list[str]:
    out = []
    for p in sorted(ROOT.rglob("*")):
        if not p.is_file() or p.suffix.lower() not in TEXT_SUFFIXES or _skip(p):
            continue
        try:
            out += [f"{p.relative_to(ROOT)}: {h}" for h in scan_text(p.read_text(errors="ignore"))]
        except Exception:
            continue
    return out


def check_office_metadata() -> list[str]:
    """Document properties are where a tool name most often survives unnoticed."""
    out = []
    for p in sorted(ROOT.rglob("*")):
        if p.suffix.lower() not in {".docx", ".xlsx", ".pptx"} or not p.is_file():
            continue
        if any(d in p.parts for d in SKIP_DIRS):
            continue
        try:
            z = zipfile.ZipFile(p)
        except Exception:
            continue
        for name in ("docProps/core.xml", "docProps/app.xml"):
            if name not in z.namelist():
                continue
            meta = z.read(name).decode(errors="ignore")
            out += [f"{p.relative_to(ROOT)} [{name}]: {h}" for h in scan_text(meta)]
            for lib in LIBRARIES:
                if lib in meta.lower():
                    out.append(f"{p.relative_to(ROOT)} [{name}]: library {lib!r} left in "
                               f"document properties — set it explicitly")
    return out


def check_temp_files() -> list[str]:
    out = []
    for pattern in (".~lock.*", "*.tmp", "~$*", ".DS_Store", "Thumbs.db"):
        for p in ROOT.rglob(pattern):
            if p.is_file() and not any(d in p.parts for d in SKIP_DIRS):
                out.append(f"{p.relative_to(ROOT)}: temporary file must not ship")
    return out


def main() -> int:
    problems = check_text_files() + check_office_metadata() + check_temp_files()
    if problems:
        print(f"Provenance check FAILED — {len(problems)} issue(s):\n")
        for x in problems:
            print("  -", x)
        return 1
    print("Provenance check passed.")
    print("  No authoring-tool names, phrases or library stamps in any shipped file.")
    print("  ATT&CK-derived data exempt by design: MITRE's vocabulary is subject matter.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
